packages:
  - workflow
  - model
  - ui
  - test
  - software
  - block

catalog:
  "@platforma-sdk/model": ^1.22.18
  "@platforma-sdk/ui-vue": ^1.22.30
  "@platforma-sdk/workflow-tengo": ^2.9.10
  "@platforma-sdk/block-tools": ^2.5.9
  "@platforma-sdk/test": ^1.22.30
  "@platforma-sdk/tengo-builder": ^1.17.5
  "@platforma-sdk/package-builder": ^2.15.0
  "@platforma-sdk/eslint-config": ^1.0.1


  "@platforma-open/milaboratories.runenv-python-3": ^1.1.5
  
  "vue": ^3.5.12
  "vue-tsc": ^2.1.6
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.2.3

  "vite": ^5.4.11
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.1.4

  "@changesets/cli": ^2.27.9
